### ISSUE TITLE
Add Lifecycle to ignore changes

### ISSUE THREAD

**Issue by derekleegh** [spotinst/terraform-spotinst-ocean-controller#16]
Hi team,

Can we have lifecycle under the deployment so we can choose to ignore changes?

I have a use case:
- I need to patch the controller to install on an another VNG once the deployment complete. I can't use the nodeSelector because the node that's spinned up on first launch is random and might not be the node I need the pod to be in.

**Comment by dominik-wa-MA** [comment]
Hello, any progress with that?

**Comment by sharadkesarwani** [comment]
Hi @guohaolee ,
We are looking into this ticket and unable to understand exact issue, could you please explain issue in detail?
What changes are you looking to ignore and why?

**Comment by derekleegh** [comment]
@sharadkesarwani IT's been a year since I worked on this. 

If I remember correctly,  we need this deployment to control what nodes to spin up/ down. On first deployment, it always goes to the default node and VNG but in reality, that's not the node I want it to be in. 

Giving the ability to ignore changes means we can either choose to manually move the pod to another VNG without affecting the terraform as there might be edge cases where we want this pod to live in different VNG with different type of instance setup. 

I think that was my use case.

**Comment by anuragsharma-123** [comment]
Ocean Controller V1 is being deprecated. Please migrate to Ocean Controller V2. 
This issue is closed.
