### ISSUE TITLE
Question about input_image_pull_policy

### ISSUE THREAD

**Issue by krzysztof-magosa** [spotinst/terraform-spotinst-ocean-controller#22]
I would like to ask what's the reasoning behind setting default of `input_image_pull_policy` to `Always`?
In case there is any problem with docker registry restart of container may cause outage.
IMO `IfNotPresent` would make more sense.

**Comment by chandra1-n** [comment]
@krzysztof-magosa Could you give more details on this, which resource are you facing this problem?

**Comment by anuragsharma-123** [comment]
Ocean Controller V1 is being deprecated. Please migrate to Ocean Controller V2. 
This issue is closed.
