### ISSUE TITLE
this Module will not support with ks8 1.24

### ISSUE THREAD

**Issue by ankitchaubey** [spotinst/terraform-spotinst-ocean-controller#23]
https://github.com/hashicorp/terraform-provider-kubernetes/issues/1724

error you will see 

```
Error: Waiting for default secret of "kube-system/spotinst-kubernetes-cluster-controller" to appear

  on .terraform/modules/bjn_eks_carder.bjn_eks_spotinst.spotinst_ocean_controller/main.tf line 43, in resource "kubernetes_service_account" "this":
  43: resource "kubernetes_service_account" "this" {
```

I see that since Kubernetes 1.24.0, service accounts no longer get this secret automatically generated (with or without automount_service_account_token set)

Terrafrom version: 13.7 
kubernetes v2.3.2

**Comment by stevenfeltner** [comment]
@chandra1-n @anuragsharma-123 Can we review this

**Comment by priyadsilva** [comment]
Any update on this issue? Its failing for eks v1.24

**Comment by chandra1-n** [comment]
> Any update on this issue? Its failing for eks v1.24

fix is in-progress.

**Comment by krzysztof-magosa** [comment]
EKS 1.25 is out there, any idea when it will be ready?

**Comment by stevenfeltner** [comment]
@krzysztof-magosa the newer version of the module has corrected this. Can you please retry? Alternatively, you can destroy the controller module and redeploy fresh with the latest version.

**Comment by narviq** [comment]
Getting the same issue with
```
module "ocean-controller" {
  source             = "spotinst/ocean-controller/spotinst"
  version            = "0.49.0"
  controller_version = "1.0.95"
```
EKS 1.25

```
│ Error: Waiting for default secret of "kube-system/controller-service-account-name" to appear
│  
│   with module.ocean-controller.kubernetes_service_account.this[0],
│   on .terraform/modules/ocean-controller/main.tf line 55, in resource "kubernetes_service_account" "this": 
│   55: resource "kubernetes_service_account" "this" {
```

EDIT: Eventually I was able to successfully apply. Not sure if the reason was upgrading hashicorp/kubernetes from 2.8.0 to 2.23.0 or running apply twice, as mentioned [here](https://github.com/hashicorp/terraform-provider-kubernetes/issues/2005#issuecomment-1551294468)

**Comment by anuragsharma-123** [comment]
@ankitchaubey - Can you please try the latest ocean controller TF module and let us know if it works for you.

**Comment by anuragsharma-123** [comment]
Ocean Controller V1 is being deprecated. Please migrate to Ocean Controller V2. 
This issue is closed.
