### ISSUE TITLE
Update controller to fix `Update your controller` warning

### ISSUE THREAD

**Issue by mrsiejas** [spotinst/terraform-spotinst-ocean-controller#25]
Please update the controller to fix `Your Spot Kubernetes Controller is not up to date. Update your controller to the latest version (Latest controller version 1.0.87)`. Using Terraform:

Provider (latest)
```
spotinst = {
  source  = "spotinst/spotinst"
  version = "1.95.2"
}
```

Controller (latest)
```
module "ocean-controller" {
  source  = "spotinst/ocean-controller/spotinst"
  version = "0.41.0"
```

The above two should be in sync and released simultaneously (or at least around the same time) to avoid controller warnings.

**Comment by stevenfeltner** [comment]
@chandra1-n Can we instead pull from the registry the latest version instead of using a variable: https://github.com/spotinst/terraform-spotinst-ocean-controller/blob/master/main.tf#L362

**Comment by anuragsharma-123** [comment]
Both Ocean Controller and TF are in sync now. 
We are not going ahead with pulling the latest version from the registry right now, because each change in the controller has to be evaluated and tested from the TF side. Sometimes, it may involve more than just upgrading the version.
