### ISSUE TITLE
Please fix integration with auto-update of controller - no new version was released for longer time

### ISSUE THREAD

**Issue by hajdukda** [spotinst/terraform-spotinst-ocean-controller#31]
Title,

We are getting complaints from terraform that controller is already available in newer version and it will override auto-update changes

**Comment by chandra1-n** [comment]
@hajdukda could you provide the below details:
cloud provider:
kubernetes version:
kubernetes-controller version:
terraform-spotinst-ocean-controller module version:

**Comment by hajdukda** [comment]
AWS
1.24
kubernetes-cluster-controller:1.0.89
version = "0.42.0"

**Comment by chandra1-n** [comment]
@hajdukda we have released terraform-spotinst-ocean-controller module version to 0.43.0 2 days ago, could you try updating that please.

**Comment by hajdukda** [comment]
Does it contain already the fixes to default-token issue in 1.24 ?

**Comment by chandra1-n** [comment]
fix is in-progress, it will be released by next week

**Comment by anuragsharma-123** [comment]
We are up-to-date with the ocean controller releases now. Thanks for pointing it out earlier. Closing this comment.
