### ISSUE TITLE
Cluster controller does not install correctly

### ISSUE THREAD

**Issue by apaterson-ecs** [spotinst/terraform-spotinst-ocean-controller#5]
During deployments of SptInst Ocean we run into the following error occasionally:

module.ocean-eks.module.ocean-controller.kubernetes_deployment.this[0]: Still creating... [10m0s elapsed]
ERROR   2020-11-26 11:44:04    
ERROR   2020-11-26 11:44:04    Error: Waiting for rollout to finish: 0 of 1 updated replicas are available...

Not entirely sure why the controller is not deploying correctly. Sometimes we have to keep removing the environment entirely then starting again and then it works.

Do you know why we would be getting this error?

**Comment by apaterson-ecs** [comment]
In fact this is related to docker rate limit. Closing.

**Comment by Spiroman** [comment]
@apaterson-ecs Could you please elaborate on how you solved this issue? 
I'm getting the same "timeout" issue, and can't see how it's related to docker rate.
