### ISSUE TITLE
Terraform plan always shows changes to apply

### ISSUE THREAD

**Issue by simonweil** [spotinst/terraform-spotinst-ocean-controller#8]
Hi,

We are using spotinst ocean controller and are facing the following issue.
Everytime we run `terraform plan/apply` there is always a change that needs to be applied:

```
  # module.spotinst_ocean_cluster.module.ocean-controller.kubernetes_deployment.this[0] will be updated in-place
  ~ resource "kubernetes_deployment" "this" {
.
.
.
.
                  ~ toleration {
                      + effect             = "NoExecute"
                      ~ key                = "node-role.kubernetes.io/master" -> "node.kubernetes.io/not-ready"
                        operator           = "Exists"
                      + toleration_seconds = "150"
                    }
                  + toleration {
                      + effect             = "NoExecute"
                      + key                = "node.kubernetes.io/unreachable"
                      + operator           = "Exists"
                      + toleration_seconds = "150"
                    }
                  + toleration {
                      + key      = "node-role.kubernetes.io/master"
                      + operator = "Exists"
                    }
                }
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.```

How can it be fixed?
Thanks

**Comment by rogersd** [comment]
I've been getting this for months.  It drives me nuts.

**Comment by liranp** [comment]
Unfortunately, those tolerations are currently [ignored](https://github.com/hashicorp/terraform-provider-kubernetes/blob/v2.0.3/kubernetes/structures_pod.go#L255-L259) by the Kubernetes provider to avoid diffs when other ones are added by the API server. See https://github.com/hashicorp/terraform-provider-kubernetes/issues/955.

**Comment by dimos-tdb** [comment]
> Unfortunately, those tolerations are currently [ignored](https://github.com/hashicorp/terraform-provider-kubernetes/blob/v2.0.3/kubernetes/structures_pod.go#L255-L259) by the Kubernetes provider to avoid diffs when other ones are added by the API server. See [hashicorp/terraform-provider-kubernetes#955](https://github.com/hashicorp/terraform-provider-kubernetes/issues/955).

@liranp , it appears that only tolerations with the `node.kubernetes.io/` prefix are ignored, so basically these ones here:
https://github.com/spotinst/terraform-spotinst-ocean-controller/blob/f664a2c69425e3685ef76e7d9860f9330059e760/main.tf#L521-L533

However these specific tolerations are automatically added to all pods by k8s,  with `toleration_seconds = 300` (https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) . So if there isn't a hard requirement  for 150 seconds on the ocean controller, it should be safe to completely remove them and fix this issue.

**Comment by liranp** [comment]
Thank you for your suggestion, @dimos-tdb. We have shortened the default `toleranceSeconds` value to 150 to reduce the recovery time of the controller in the event of an unreachable node. We've [moved those tolerations into a variable](https://github.com/spotinst/terraform-spotinst-ocean-controller/blob/v0.21.0/variables.tf#L99-L112) that allows you to override this behavior (as well as workaround the upstream issue) by setting the variable to an empty list.

**Comment by liranp** [comment]
Thank you for your suggestion, @dimos-tdb. Initially, we shortened the default `toleranceSeconds` value to 150 to reduce the recovery time of the controller in the event of an unreachable node. We have [moved those tolerations into a variable](https://github.com/spotinst/terraform-spotinst-ocean-controller/blob/v0.21.0/variables.tf#L99-L112) that allows you to override this behavior (as well as workaround the upstream issue) by setting the variable to an empty list.

**Comment by liranp** [comment]
Thank you for your suggestion, @dimos-tdb. Initially, we shortened the default `toleranceSeconds` value to 150 to reduce the recovery time of the controller in the event of an unreachable node. We have [moved those tolerations into a variable](https://github.com/spotinst/terraform-spotinst-ocean-controller/blob/v0.21.0/variables.tf#L99-L112) that allows you to override this behavior (as well as workaround the upstream issue) by setting the variable to an empty list:

```hcl
module "ocean-controller" {
  source  = "spotinst/ocean-controller/spotinst"

  # credentials
  spotinst_token   = "<redacted>"
  spotinst_account = "<redacted>"

  # configuration
  cluster_identifier = "foo"

  # remove default tolerations
  tolerations = []  
}
```

**Comment by simonweil** [comment]
As these tolerations are ignored by the kubernetes provider they don't even have any affect.
How about removing them by default and bring them back once the provider issue is fixed?

See this explanation:
https://github.com/hashicorp/terraform-provider-kubernetes/issues/955#issuecomment-681022027
